# Template used from
# https://github.com/plusjade/jekyll-bootstrap/blob/master/_config.yml

# theme
# https://github.com/dottru/so-simple-theme
title: dottru | showcase
description: because programming is hard
logo: site-logo.png
discus_shortname: dottru
url: http://dottru.github.io

owner:
  name: Michael Watson
  avatar: your-photo.jpg
  email: dottru@gmail.com
  github: jmkogut

production_url: http://dottru.github.io
BASE_PATH: false

google_analytics: 'UA-43844239-1'
pygments: true
permalink:   /:categories/:title
markdown: kramdown
